# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openLoop.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(556, 335)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.onButton = QtWidgets.QPushButton(self.centralwidget)
        self.onButton.setGeometry(QtCore.QRect(300, 120, 131, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.onButton.setFont(font)
        self.onButton.setObjectName("onButton")
        self.freq_mod = QtWidgets.QLineEdit(self.centralwidget)
        self.freq_mod.setGeometry(QtCore.QRect(30, 120, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.freq_mod.setFont(font)
        self.freq_mod.setClearButtonEnabled(False)
        self.freq_mod.setObjectName("freq_mod")
        self.freq_mod_label = QtWidgets.QLabel(self.centralwidget)
        self.freq_mod_label.setGeometry(QtCore.QRect(30, 90, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.freq_mod_label.setFont(font)
        self.freq_mod_label.setObjectName("freq_mod_label")
        self.amp_mod_label = QtWidgets.QLabel(self.centralwidget)
        self.amp_mod_label.setGeometry(QtCore.QRect(30, 170, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.amp_mod_label.setFont(font)
        self.amp_mod_label.setObjectName("amp_mod_label")
        self.amp_mod = QtWidgets.QLineEdit(self.centralwidget)
        self.amp_mod.setGeometry(QtCore.QRect(30, 200, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.amp_mod.setFont(font)
        self.amp_mod.setClearButtonEnabled(False)
        self.amp_mod.setObjectName("amp_mod")
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(400, 10, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.connectButton.setFont(font)
        self.connectButton.setObjectName("connectButton")
        self.com_uart = QtWidgets.QLineEdit(self.centralwidget)
        self.com_uart.setGeometry(QtCore.QRect(300, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.com_uart.setFont(font)
        self.com_uart.setClearButtonEnabled(False)
        self.com_uart.setObjectName("com_uart")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(30, 40, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sendButton.setFont(font)
        self.sendButton.setObjectName("sendButton")
        self.conection_label = QtWidgets.QLabel(self.centralwidget)
        self.conection_label.setGeometry(QtCore.QRect(300, 70, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.conection_label.setFont(font)
        self.conection_label.setObjectName("conection_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 556, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.onButton.setText(_translate("MainWindow", "ON"))
        self.freq_mod.setText(_translate("MainWindow", "10.0"))
        self.freq_mod_label.setText(_translate("MainWindow", "Frecuencia moduladora"))
        self.amp_mod_label.setText(_translate("MainWindow", "Amplitud moduladora"))
        self.amp_mod.setText(_translate("MainWindow", "0.01"))
        self.connectButton.setText(_translate("MainWindow", "CONECT"))
        self.com_uart.setText(_translate("MainWindow", "COMX"))
        self.sendButton.setText(_translate("MainWindow", "SEND"))
        self.conection_label.setText(_translate("MainWindow", "Not connected"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
